# Generated by Django 3.2.12 on 2023-03-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smap', '0003_auto_20230310_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=100)),
                ('dept', models.CharField(default='', max_length=50)),
                ('clas', models.CharField(default='', max_length=5)),
                ('sub', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='smap/images')),
            ],
        ),
    ]
